// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/proto/concerto_admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestTakerId   uint64                 `protobuf:"varint,1,opt,name=test_taker_id,json=testTakerId,proto3" json:"test_taker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequest) Reset() {
	*x = GetSessionStatusRequest{}
	mi := &file_api_proto_concerto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequest) ProtoMessage() {}

func (x *GetSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_concerto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_concerto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionStatusRequest) GetTestTakerId() uint64 {
	if x != nil {
		return x.TestTakerId
	}
	return 0
}

type GetSessionStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TestTakerId       uint64                 `protobuf:"varint,1,opt,name=test_taker_id,json=testTakerId,proto3" json:"test_taker_id,omitempty"`
	HasActiveSession  bool                   `protobuf:"varint,2,opt,name=has_active_session,json=hasActiveSession,proto3" json:"has_active_session,omitempty"`
	CanUpdateAttempts bool                   `protobuf:"varint,3,opt,name=can_update_attempts,json=canUpdateAttempts,proto3" json:"can_update_attempts,omitempty"`
	SessionId         int32                  `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionStartDate  string                 `protobuf:"bytes,5,opt,name=session_start_date,json=sessionStartDate,proto3" json:"session_start_date,omitempty"` // Формат: YYYY-MM-DD HH:MM:SS
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSessionStatusResponse) Reset() {
	*x = GetSessionStatusResponse{}
	mi := &file_api_proto_concerto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusResponse) ProtoMessage() {}

func (x *GetSessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_concerto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_concerto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionStatusResponse) GetTestTakerId() uint64 {
	if x != nil {
		return x.TestTakerId
	}
	return 0
}

func (x *GetSessionStatusResponse) GetHasActiveSession() bool {
	if x != nil {
		return x.HasActiveSession
	}
	return false
}

func (x *GetSessionStatusResponse) GetCanUpdateAttempts() bool {
	if x != nil {
		return x.CanUpdateAttempts
	}
	return false
}

func (x *GetSessionStatusResponse) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetSessionStatusResponse) GetSessionStartDate() string {
	if x != nil {
		return x.SessionStartDate
	}
	return ""
}

type AdminUpdateAttemptsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	TestTakerId      uint64                 `protobuf:"varint,2,opt,name=test_taker_id,json=testTakerId,proto3" json:"test_taker_id,omitempty"`
	CurrentAttempts  int32                  `protobuf:"varint,3,opt,name=current_attempts,json=currentAttempts,proto3" json:"current_attempts,omitempty"`
	CurrentUsed      int32                  `protobuf:"varint,4,opt,name=current_used,json=currentUsed,proto3" json:"current_used,omitempty"`
	AttemptsToRefund int32                  `protobuf:"varint,5,opt,name=attempts_to_refund,json=attemptsToRefund,proto3" json:"attempts_to_refund,omitempty"`
	ProductVariant   int32                  `protobuf:"varint,6,opt,name=product_variant,json=productVariant,proto3" json:"product_variant,omitempty"`
	ProductLanguage  string                 `protobuf:"bytes,7,opt,name=product_language,json=productLanguage,proto3" json:"product_language,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminUpdateAttemptsRequest) Reset() {
	*x = AdminUpdateAttemptsRequest{}
	mi := &file_api_proto_concerto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateAttemptsRequest) ProtoMessage() {}

func (x *AdminUpdateAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_concerto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateAttemptsRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_concerto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUpdateAttemptsRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AdminUpdateAttemptsRequest) GetTestTakerId() uint64 {
	if x != nil {
		return x.TestTakerId
	}
	return 0
}

func (x *AdminUpdateAttemptsRequest) GetCurrentAttempts() int32 {
	if x != nil {
		return x.CurrentAttempts
	}
	return 0
}

func (x *AdminUpdateAttemptsRequest) GetCurrentUsed() int32 {
	if x != nil {
		return x.CurrentUsed
	}
	return 0
}

func (x *AdminUpdateAttemptsRequest) GetAttemptsToRefund() int32 {
	if x != nil {
		return x.AttemptsToRefund
	}
	return 0
}

func (x *AdminUpdateAttemptsRequest) GetProductVariant() int32 {
	if x != nil {
		return x.ProductVariant
	}
	return 0
}

func (x *AdminUpdateAttemptsRequest) GetProductLanguage() string {
	if x != nil {
		return x.ProductLanguage
	}
	return ""
}

type AdminUpdateAttemptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TestTakerId   uint64                 `protobuf:"varint,4,opt,name=test_taker_id,json=testTakerId,proto3" json:"test_taker_id,omitempty"`
	AttemptsTotal int32                  `protobuf:"varint,5,opt,name=attempts_total,json=attemptsTotal,proto3" json:"attempts_total,omitempty"`
	AttemptsUsed  int32                  `protobuf:"varint,6,opt,name=attempts_used,json=attemptsUsed,proto3" json:"attempts_used,omitempty"`
	Refund        int32                  `protobuf:"varint,7,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateAttemptsResponse) Reset() {
	*x = AdminUpdateAttemptsResponse{}
	mi := &file_api_proto_concerto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateAttemptsResponse) ProtoMessage() {}

func (x *AdminUpdateAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_concerto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateAttemptsResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdateAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_concerto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUpdateAttemptsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminUpdateAttemptsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AdminUpdateAttemptsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AdminUpdateAttemptsResponse) GetTestTakerId() uint64 {
	if x != nil {
		return x.TestTakerId
	}
	return 0
}

func (x *AdminUpdateAttemptsResponse) GetAttemptsTotal() int32 {
	if x != nil {
		return x.AttemptsTotal
	}
	return 0
}

func (x *AdminUpdateAttemptsResponse) GetAttemptsUsed() int32 {
	if x != nil {
		return x.AttemptsUsed
	}
	return 0
}

func (x *AdminUpdateAttemptsResponse) GetRefund() int32 {
	if x != nil {
		return x.Refund
	}
	return 0
}

var File_api_proto_concerto_admin_proto protoreflect.FileDescriptor

const file_api_proto_concerto_admin_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/concerto_admin.proto\x12\x11concerto.admin.v1\"=\n" +
	"\x17GetSessionStatusRequest\x12\"\n" +
	"\rtest_taker_id\x18\x01 \x01(\x04R\vtestTakerId\"\xe9\x01\n" +
	"\x18GetSessionStatusResponse\x12\"\n" +
	"\rtest_taker_id\x18\x01 \x01(\x04R\vtestTakerId\x12,\n" +
	"\x12has_active_session\x18\x02 \x01(\bR\x10hasActiveSession\x12.\n" +
	"\x13can_update_attempts\x18\x03 \x01(\bR\x11canUpdateAttempts\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\x05R\tsessionId\x12,\n" +
	"\x12session_start_date\x18\x05 \x01(\tR\x10sessionStartDate\"\xb3\x02\n" +
	"\x1aAdminUpdateAttemptsRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\"\n" +
	"\rtest_taker_id\x18\x02 \x01(\x04R\vtestTakerId\x12)\n" +
	"\x10current_attempts\x18\x03 \x01(\x05R\x0fcurrentAttempts\x12!\n" +
	"\fcurrent_used\x18\x04 \x01(\x05R\vcurrentUsed\x12,\n" +
	"\x12attempts_to_refund\x18\x05 \x01(\x05R\x10attemptsToRefund\x12'\n" +
	"\x0fproduct_variant\x18\x06 \x01(\x05R\x0eproductVariant\x12)\n" +
	"\x10product_language\x18\a \x01(\tR\x0fproductLanguage\"\x83\x02\n" +
	"\x1bAdminUpdateAttemptsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\"\n" +
	"\rtest_taker_id\x18\x04 \x01(\x04R\vtestTakerId\x12%\n" +
	"\x0eattempts_total\x18\x05 \x01(\x05R\rattemptsTotal\x12#\n" +
	"\rattempts_used\x18\x06 \x01(\x05R\fattemptsUsed\x12\x16\n" +
	"\x06refund\x18\a \x01(\x05R\x06refund2\xf9\x01\n" +
	"\x14ConcertoAdminService\x12k\n" +
	"\x10GetSessionStatus\x12*.concerto.admin.v1.GetSessionStatusRequest\x1a+.concerto.admin.v1.GetSessionStatusResponse\x12t\n" +
	"\x13AdminUpdateAttempts\x12-.concerto.admin.v1.AdminUpdateAttemptsRequest\x1a..concerto.admin.v1.AdminUpdateAttemptsResponseBBZ@github.com/Makanov-Nurzhan/concerto-gRPC/api/gen/adminv1;adminv1b\x06proto3"

var (
	file_api_proto_concerto_admin_proto_rawDescOnce sync.Once
	file_api_proto_concerto_admin_proto_rawDescData []byte
)

func file_api_proto_concerto_admin_proto_rawDescGZIP() []byte {
	file_api_proto_concerto_admin_proto_rawDescOnce.Do(func() {
		file_api_proto_concerto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_concerto_admin_proto_rawDesc), len(file_api_proto_concerto_admin_proto_rawDesc)))
	})
	return file_api_proto_concerto_admin_proto_rawDescData
}

var file_api_proto_concerto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_concerto_admin_proto_goTypes = []any{
	(*GetSessionStatusRequest)(nil),     // 0: concerto.admin.v1.GetSessionStatusRequest
	(*GetSessionStatusResponse)(nil),    // 1: concerto.admin.v1.GetSessionStatusResponse
	(*AdminUpdateAttemptsRequest)(nil),  // 2: concerto.admin.v1.AdminUpdateAttemptsRequest
	(*AdminUpdateAttemptsResponse)(nil), // 3: concerto.admin.v1.AdminUpdateAttemptsResponse
}
var file_api_proto_concerto_admin_proto_depIdxs = []int32{
	0, // 0: concerto.admin.v1.ConcertoAdminService.GetSessionStatus:input_type -> concerto.admin.v1.GetSessionStatusRequest
	2, // 1: concerto.admin.v1.ConcertoAdminService.AdminUpdateAttempts:input_type -> concerto.admin.v1.AdminUpdateAttemptsRequest
	1, // 2: concerto.admin.v1.ConcertoAdminService.GetSessionStatus:output_type -> concerto.admin.v1.GetSessionStatusResponse
	3, // 3: concerto.admin.v1.ConcertoAdminService.AdminUpdateAttempts:output_type -> concerto.admin.v1.AdminUpdateAttemptsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_concerto_admin_proto_init() }
func file_api_proto_concerto_admin_proto_init() {
	if File_api_proto_concerto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_concerto_admin_proto_rawDesc), len(file_api_proto_concerto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_concerto_admin_proto_goTypes,
		DependencyIndexes: file_api_proto_concerto_admin_proto_depIdxs,
		MessageInfos:      file_api_proto_concerto_admin_proto_msgTypes,
	}.Build()
	File_api_proto_concerto_admin_proto = out.File
	file_api_proto_concerto_admin_proto_goTypes = nil
	file_api_proto_concerto_admin_proto_depIdxs = nil
}
