// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/concerto_admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConcertoAdminService_GetSessionStatus_FullMethodName    = "/concerto.admin.v1.ConcertoAdminService/GetSessionStatus"
	ConcertoAdminService_AdminUpdateAttempts_FullMethodName = "/concerto.admin.v1.ConcertoAdminService/AdminUpdateAttempts"
)

// ConcertoAdminServiceClient is the client API for ConcertoAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConcertoAdminServiceClient interface {
	GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*GetSessionStatusResponse, error)
	AdminUpdateAttempts(ctx context.Context, in *AdminUpdateAttemptsRequest, opts ...grpc.CallOption) (*AdminUpdateAttemptsResponse, error)
}

type concertoAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConcertoAdminServiceClient(cc grpc.ClientConnInterface) ConcertoAdminServiceClient {
	return &concertoAdminServiceClient{cc}
}

func (c *concertoAdminServiceClient) GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*GetSessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStatusResponse)
	err := c.cc.Invoke(ctx, ConcertoAdminService_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concertoAdminServiceClient) AdminUpdateAttempts(ctx context.Context, in *AdminUpdateAttemptsRequest, opts ...grpc.CallOption) (*AdminUpdateAttemptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateAttemptsResponse)
	err := c.cc.Invoke(ctx, ConcertoAdminService_AdminUpdateAttempts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConcertoAdminServiceServer is the server API for ConcertoAdminService service.
// All implementations must embed UnimplementedConcertoAdminServiceServer
// for forward compatibility.
type ConcertoAdminServiceServer interface {
	GetSessionStatus(context.Context, *GetSessionStatusRequest) (*GetSessionStatusResponse, error)
	AdminUpdateAttempts(context.Context, *AdminUpdateAttemptsRequest) (*AdminUpdateAttemptsResponse, error)
	mustEmbedUnimplementedConcertoAdminServiceServer()
}

// UnimplementedConcertoAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConcertoAdminServiceServer struct{}

func (UnimplementedConcertoAdminServiceServer) GetSessionStatus(context.Context, *GetSessionStatusRequest) (*GetSessionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedConcertoAdminServiceServer) AdminUpdateAttempts(context.Context, *AdminUpdateAttemptsRequest) (*AdminUpdateAttemptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateAttempts not implemented")
}
func (UnimplementedConcertoAdminServiceServer) mustEmbedUnimplementedConcertoAdminServiceServer() {}
func (UnimplementedConcertoAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeConcertoAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConcertoAdminServiceServer will
// result in compilation errors.
type UnsafeConcertoAdminServiceServer interface {
	mustEmbedUnimplementedConcertoAdminServiceServer()
}

func RegisterConcertoAdminServiceServer(s grpc.ServiceRegistrar, srv ConcertoAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedConcertoAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConcertoAdminService_ServiceDesc, srv)
}

func _ConcertoAdminService_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcertoAdminServiceServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConcertoAdminService_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcertoAdminServiceServer).GetSessionStatus(ctx, req.(*GetSessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConcertoAdminService_AdminUpdateAttempts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateAttemptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcertoAdminServiceServer).AdminUpdateAttempts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConcertoAdminService_AdminUpdateAttempts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcertoAdminServiceServer).AdminUpdateAttempts(ctx, req.(*AdminUpdateAttemptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConcertoAdminService_ServiceDesc is the grpc.ServiceDesc for ConcertoAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConcertoAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "concerto.admin.v1.ConcertoAdminService",
	HandlerType: (*ConcertoAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSessionStatus",
			Handler:    _ConcertoAdminService_GetSessionStatus_Handler,
		},
		{
			MethodName: "AdminUpdateAttempts",
			Handler:    _ConcertoAdminService_AdminUpdateAttempts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/concerto_admin.proto",
}
